#!/usr/bin/env bash
# Display "Best School" 10 times, But for the 9th iteration display "Best School" then "Hi". Use while loop and if statement.

myvar=1

while [ $myvar -le 10 ]
do
	echo "Best School"
	if [ $myvar -eq 9 ]
	then
		echo "Hi"
	fi
	myvar=$(( myvar + 1))
done
